### ISSUE TITLE
Pick and place

### ISSUE THREAD

**Issue by KheireddineAzzez** [WEKIT-ECS/MIRAGE-XR#1563]
MirageXR: V2.3
Hardware: Ipad Pro + LIDAR and cellular

Issue :
Regarding the pick and place functionality, the arrow object is not able to detect the collided object.

![Screenshot 2023-09-16 at 13 24 23 (1)](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/59838139/dfadd3c5-767a-43b1-96e7-ee82b6da1808)

**Comment by fwild** [comment]
This is a misunderstanding: clicking on the "change model" button near the arrow, you can assign a 3D model (instead of using the orange arrow). When the 3D model is then dropped to where the white sphere is, it is considered 'correct placement'. If you want to model collision, you need to create two 3D models, assign one to be used instead of the arrow, and place the white sphere over the other (resize if necessary).

**Comment by fwild** [comment]
Closing this ticket. But creating a new one to update the UI dialogue for pick and place, to make it easier and add some help text.

**Comment by fwild** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1569
