### ISSUE TITLE
When re-calibrating, the position of the existing task station diamonds should NOT reset. 

### ISSUE THREAD

**Issue by fominykh** [WEKIT-ECS/MIRAGE-XR#1576]
Currently,
When re-calibrating, the position of the existing task station diamonds is reset. They are moved close to the calibration marker. 
How to reproduce:
1. Create a new activity on an iPad Pro. Calibrate. Create several steps. Add augmentations to steps. I used 3D models, labels, and pick-and-place.
2. Use keep-alive for 3D models and labels.
3. Save locally.
4. Close the iPad for 10 minutes.
5. Open iPad. Recalibrate.
6. Observe that the task stations moved several meters from where they were. They are now very close to the calibration marker.

Should be:
The task stations should stay where they were after re-calibration.

**Comment by fwild** [comment]
This may also affect "new position of the calibration image" - as this may have the same bug then? At least one would expect that, if uncalibrated, one could use this routine to set a new location - but it also resets the position, the same way.

**Comment by fwild** [comment]
Does it make sense to get rid of the two options for calibration - and offer the possibility to move the calibration marker position only if session is calibrated already?

**Comment by fwild** [comment]
I have re-tested this today: I did exactly like above (facing towards the door when calibrating), but instead of waiting 10 min, I closed the ipad, moved to a different part of the room, facing into the opposite direction (away from the door), and opened it again. 

The result was: all the augmentations are in the new location (somewhat expected, though a 'lost tracking' warning message did not appear!). When I did the recalibration (without floor detection), I got error messages:

* [ERROR] Can't find plane with id: PlaneId
* [ERROR] Can't find GameObject with id: PlaneId
* [ERROR] Can't create arAnchor

... and the task stations were not correctly repositioned (and all augmentations remained in the wrong place).

Then I recalibrated again, but this time did the floor plane detection first and then the calibration (again "reset anchor positions" set to off), and this time the task stations were moved to their correct positions, but not all augmentations: the 3D model was still somewhere in the other part of the room (but even smaller = further away, and its boundary box looked artificially enlarged and seemed to cover half of the room - looks almost like it only set x0, y0, and z0 coordinates, but not the second coordinate of the boundary box? 

The label augmentation was rotated by 180 degrees (= only its position was set by recalibration, but not its orientation).

And the pick&place sphere is gone, the arrow is correctly placed.

I also got an error message here:
* NullReferenceException: Object reference not set to an instance of an object

Then I did the same again, fresh restart, fresh activity, moving after editing
to different part of the room, recalibrating then WITH FIRST FLOOR PLANE DETECTION 
executed, and everything worked as expected.

So: I think there is an error about floor plane that we have not caught yet, and
after this error appears, the app just becomes erratic.

**Comment by fwild** [comment]
I re-tested it again now 10 min later: got the floor plane not found error despite doing floor plane detection first - resulting in incorrect restore of positions (this time all augmentations but label were in the correct place, though, and label was both in wrong orientation AND wrong position). Then I hard quit the app, restarted, recalibrated (with the forced floor plane detection), and this time all were in the right position, only label facing 180 degrees in the opposite direction.

**Comment by fwild** [comment]
When I did it again now, somehow one of the augmentations (3D model) started believing it was being moved, quite likely because I accidentally tapped it, and it did not capture the tap release, so it remained in 'ghost mode' and kept on shifting around. 

I think this is related to the bug where tapping on the menu can move 3D models (#1688) - hitting 'recalibrate' in the menu must have accidentally started moving the 3D model, and since we then reset positions, it broke the 'moving' interaction, resulting in this bug.

**Comment by fominykh** [comment]
I have seen some of these issues recently, but did not manage to reproduce exactly when they happen. For example, the very large bounding box of the 3D models.
