### ISSUE TITLE
Mobile: rotation / movement of task station is too fiddly

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#689]
In GitLab by @wild on Nov 2, 2021, 16:13

It is rather tricky to move the task station around on mobile UI - maybe we need to switch to a "joystick" approach? With an on screen joystick and up/down lever to move the task station around alternatively? At the moment, the diamons are too easily moved by users into far distance.

**Comment by wekitecs** [comment]
In GitLab by @wild on Nov 9, 2021, 17:43

I think placement of task stations could be like depicted here:
https://www.youtube.com/watch?v=orV8d3A32Ew

User has to map the environment; then can see how the shadow of the task station moves over the map; tap to place - and then use a slider to decide, whether the task station needs to move up or down (0m to 3m, default value 1.20m).

**Comment by fwild** [comment]
From dupe ticket:

A user adds: "Lack of precision (Using a phone didn't allow for precision when placing objects in space)." (Google Pixel 6 Pro, Android 12)

We need to find a better way to move the task stations around - at the moment, users often shift the task station into infinity - then causing all sorts of other problems, because the task station is far away. Can we maybe do something with hovering a ring over the spatial map - plus an additional screen-space lever to move the task station up or down?
