### ISSUE TITLE
Spatial UX: SR1b: Lighting

### ISSUE THREAD

**Issue by wekitecs** [WEKIT-ECS/MIRAGE-XR#845]
Many augmentations are not properly lit: the 3D models are often almost invisible; the glyphs (e.g. red arrow) often not visible; the 3D drawing is almost impossible to see.

Maybe a point light should be added from the place of the task station? Or allow users to place another light source (point light or spot light) in the scene? As an action glyph?

Related to https://github.com/WEKIT-ECS/MIRAGE-XR/issues/783

**Comment by wekitecs** [comment]
In GitLab by @wild on Mar 10, 2022, 15:28

And there is a weird shadow on the ghost when you look at recordings:

![Screenshot_2022-03-10_at_14.27.49](https://platform.xr4all.eu/wekit-ecs/mirage-xr/uploads/13e42393e0be6ffdde04a2f625ce4131/Screenshot_2022-03-10_at_14.27.49.png)

**Comment by wekitecs** [comment]
In GitLab by @wild on Mar 10, 2022, 15:28

This weird shadow does only happen on Hololens - not on iPad.

**Comment by wekitecs** [comment]
In GitLab by @s.thanyadit on Mar 23, 2022, 17:51

marked this issue as related to #783

**Comment by fwild** [comment]
This is what the lighting should look like...: 

<img width="399" alt="Screenshot 2022-06-21 at 14 42 00" src="https://user-images.githubusercontent.com/183296/174814455-6f867693-d18c-4a33-987c-095c41a6da38.png">

**Comment by fwild** [comment]
I propose we add a directional light as child of the Main camera, which is slightly elevated (0.5m above?) and facing slightly down, so that it produces nice shadows - with a not too harsh light intensity? And call it "UserTorchLight" so we remember what it is?

![image](https://github.com/WEKIT-ECS/MIRAGE-XR/assets/183296/93fe281c-8cfd-4962-88ff-609d972f27dc)
